# Generated by Django 4.2 on 2023-05-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='educations',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='info',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='summary_text',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='technical_projects',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='technical_skills',
        ),
    ]
