# Generated by Django 4.2 on 2023-05-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='u_profile',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='u_profile',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='u_profile',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='u_profile',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='u_profile',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='technicalproject',
            old_name='u_profile',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='technicalskill',
            old_name='u_profile',
            new_name='user_profile',
        ),
    ]
